import '@/styles/global-styles.css';
import '@/styles/design-tokens.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '@/components/header/Header';
import styles from './_app.module.css';
import Footer from '@/components/footer/Footer';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import 'react-loading-skeleton/dist/skeleton.css'

export default function App({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <div className={styles.container}>
          <Header />
          <div className={styles.content}>
            <Component {...pageProps} />
            <ReactQueryDevtools initialIsOpen={false} />
          </div>
          <Footer />
        </div>
      </QueryClientProvider>
    </>
  );
}
