import '@/styles/global-styles.css';
import '@/styles/design-tokens.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '@/components/Header/Header';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <Component {...pageProps} />
      </div>
    </>
  );
}
