import '@/styles/global-styles.css';
import '@/styles/design-tokens.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '@/components/header/Header';
import styles from './_app.module.css';
import Footer from '@/components/footer/Footer';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <div className={styles.content}>
          <Component {...pageProps} />
        </div>
        <Footer />
      </div>
    </>
  );
}
